name: Sync label data to Ozone

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      PRIME_OZONE_SERVICE_USER_DID: ${{ secrets.PRIME_OZONE_SERVICE_USER_DID }}
      PRIME_BSKY_USER: ${{ secrets.PRIME_BSKY_USER }}
      PRIME_BSKY_PASS: ${{ secrets.PRIME_BSKY_PASS }}
      POKEMON_OZONE_SERVICE_USER_DID: ${{ secrets.POKEMON_OZONE_SERVICE_USER_DID }}
      POKEMON_BSKY_USER: ${{ secrets.POKEMON_BSKY_USER }}
      POKEMON_BSKY_PASS: ${{ secrets.POKEMON_BSKY_PASS }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npx tsx src/uploadLocalizationsToLabeler.ts
